import '../styles/globals.scss'
import type { Metadata } from 'next'
import { inter } from '@/utils/fonts/font'
import { AuthProvider } from '@/contexts/Authentication/AuthContext'

export const metadata: Metadata = {
  title: 'Stuuky',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
