import '../styles/globals.scss'
import type { Metadata } from 'next'
import { inter } from '@/utils/fonts/font'
import ApolloWrapper from '@/lib/apollo/ApolloWrapper'

export const metadata: Metadata = {
  title: 'Stuuky',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ApolloWrapper>
      <html lang="pt-br">
        <body className={inter.className}>
          {children}
        </body>
      </html>
    </ApolloWrapper>
  )
}
